CREATE TABLE IF NOT EXISTS Results (
  pk        INTEGER  PRIMARY KEY AUTOINCREMENT,
  date 		  TEXT     NOT NULL,
  serverId 	INTEGER  NOT NULL,
  spikes   	INTEGER	 NOT NULL,
  events   	INTEGER	 NOT NULL
);
