CREATE TABLE IF NOT EXISTS Results (
  pk        INTEGER  PRIMARY KEY AUTOINCREMENT,
  date 		  TEXT     NOT NULL,
  spikes   	INTEGER	 NOT NULL,
  events   	INTEGER	 NOT NULL
);

CREATE TABLE IF NOT EXISTS Scores (
  pk      INTEGER PRIMARY KEY AUTOINCREMENT,
  date    TEXT  NOT NULL,
  zcpu  INTEGER NOT NULL,
  zmem  INTEGER NOT NULL,
);