CREATE TABLE IF NOT EXISTS Results (
	pk INTEGER PRIMARY KEY AUTOINCREMENT,
	spike INTEGER NOT NULL,
	time TEXT NOT NULL,
	severity INTEGER NOT NULL,
	server_id INTEGER NOT NULL
	);

CREATE TABLE IF NOT EXISTS 'Server' (
	pk INTEGER PRIMARY KEY AUTOINCREMENT,
	time TEXT NOT NULL,
	server_name TEXT NOT NULL,
	finished INTEGER NOT NULL
	);

