CREATE TABLE Results (
	pk 			INTEGER PRIMARY KEY AUTOINCREMENT,
	date 		TEXT	NOT NULL,
	serverId 	INTEGER	NOT NULL,
	spikeNum 	INTEGER	NOT NULL,
	eventNum 	INTEGER	NOT NULL,
	finished 	INTEGER	NOT NULL
);